---
title: "Viz part 1"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"), #station ID
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", # matching ID to station name
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Let's make a plot!

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

Pipes and stuff

```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggp_nyc_weather =
  weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggp_nyc_weather
```

## Fancy plot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name),alpha = 0.3) + # alpha sets the transparency of points
  geom_smooth(se = FALSE) # add a smooth curve
```

Plot with facets

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name) 
  # put everything other than variable name under each facet named by the variable
# facet_grid(name ~ .)
```

try assigning a specific color

```{r}
weather_df |>
  filter(name != "CentralPark_NY") |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = 0.7, size = 0.5)
#  geom_point(color = "blue")
```


Let's try a different plot. (temp is boring)

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp, alpha = 0.3)) + # assign point size by precipitation
  geom_smooth()

```

hex

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```

line and points

```{r}
weather_df |>
  filter(name == "Molokai_HI") |>
  ggplot(aes(x = date, y = tmax)) +
  geom_line(alpha = .5) +
  geom_point(size = .5)
```


## univariate plotting

histogram

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
#ggplot(weather_df, aes(x = tmax, color = name)) +
  geom_histogram()
  #geom_histogram(position = "dodge")
```


Let's use a density plot 

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.3, adjust = 0.75)
```

Using boxplots!!

```{r}
ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_boxplot()
```

Violin plot?

```{r}
ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_violin()
```

ridge plot
(density plot, but not overlapping)

```{r}
ggplot(weather_df, aes(x = tmax, y = name)) +
  geom_density_ridges()
```


## saving and embedding plots

```{r}
ggp_weather = 
	weather_df |>
	ggplot(aes(x = tmin, y = tmax)) +
  geom_point(size = .5)

ggp_nyc_weather
ggsave("results/ggp_weather.pdf", ggp_weather)
```

```{r, fig.width = 6, fig.asp = .6}
#```{r, fig.width = 6, fig.height = 12}
ggp_weather
```


